matchers:
  - id: habib-metro-cash-withdraw
    pattern: 'HABIBMETRO - Alert: (?P<datetime>[0-9-]+ [0-9:]+) (?P<account>.+) Amt (?P<amount>.+) Debited /Switch Withdrawal (?P<location>.+), Avl. Bal .+ CR'
    values:
      nature:
        type: Fixed
        config: Debit
      account:
        type: FromMatch
        config:
          group: account
          parser: null
      amount:
        type: FromMatch
        config:
          group: amount
          parser: null
      currency:
        type: Fixed
        config: PKR
      source:
        type: FromMatch
        config:
          group: location
          parser: null
      time:
        type: FromMatch
        config:
          group: datetime
          parser:
            type: FormattedDateTime
            config: '%d-%m-%y %H:%M'

  - id: js-credit-card-used
    pattern: 'Dear .+, your JS Bank credit card ending with (?P<card>.+) has been used for (?P<currency>[A-Z]+) (?P<amount>.+) at (?P<location>.+) on (?P<datetime>.+ at \d\d:\d\d:\d\d)\.'
    values:
      nature:
        type: Fixed
        config: Debit
      account:
        type: FromMatch
        config:
          group: card
          parser: null
      amount:
        type: FromMatch
        config:
          group: amount
          parser: null
      currency:
        type: FromMatch
        config:
          group: currency
          parser: null
      source:
        type: FromMatch
        config:
          group: location
          parser: null
      time:
        type: FromMatch
        config:
          group: datetime
          parser:
            type: FormattedDateTime
            config: '%d/%m/%y at %H:%M:%S'

  - id: js-credit-card-online-used
    pattern: 'Dear .+, your JS Bank credit card ending with (?P<card>.+) has been used for (?P<currency>[A-Z]+) (?P<amount>.+) at (?P<location>.+) on (?P<datetime>.+ at \d+)\.'
    values:
      nature:
        type: Fixed
        config: Debit
      account:
        type: FromMatch
        config:
          group: card
          parser: null
      amount:
        type: FromMatch
        config:
          group: amount
          parser: null
      currency:
        type: FromMatch
        config:
          group: currency
          parser: null
      source:
        type: FromMatch
        config:
          group: location
          parser: null
      time:
        type: FromMatch
        config:
          group: datetime
          parser:
            type: FormattedDateTimeWithAppend
            config:
              format: '%d/%m/%y at %H:%M'
              suffix: ':00'

  - id: js-cash-withdrawl
    pattern: 'Acct. (?P<account>.+) debited by (?P<currency>.+) (?P<amount>.+) due to (?P<reason>.+) at (?P<datetime>.+ hrs on .+).Current Balance: .+'
    values:
      nature:
        type: Fixed
        config: Debit
      account:
        type: FromMatch
        config:
          group: account
          parser: null
      amount:
        type: FromMatch
        config:
          group: amount
          parser: null
      currency:
        type: FromMatch
        config:
          group: currency
          parser: null
      source:
        type: FromMatch
        config:
          group: reason
          parser: null
      time:
        type: FromMatch
        config:
          group: datetime
          parser:
            type: FormattedDateTime
            config: '%H:%M hrs on %d-%m-%Y'
